server:
  port: 8180
  servlet:
    context-path: /app

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ONLINE_SHOP
    username: root1
    password: root1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update